---
# https://nghttp2.org/documentation/h2load-howto.html

- name: testing | git clone h2load repository
  git:
    repo: https://github.com/nghttp2/nghttp2.git
    dest: /var/tmp/nghttp2
    update: no

- name: testing | ensure h2load dependencies are present
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ testing_h2load_deps }}"
  
- name: testing | build h2load
  command: "{{ item }}"
  with_items:
    - git submodule update --init
    - autoreconf -i
    - automake
    - autoconf
    - ./configure
    - make
    - make install
  args:
    chdir: /var/tmp/nghttp2

- name: testing | executing h2load
  command: "{{ item }}"
  with_items:
    - h2load -n100000 -c100 -m10 https://localhost
